added option for advanced response (PHP-162)
symcon/Benachrichtigung pull request #10
Opened 2020-10-22 08:29 UTC by TillBrede

2020-10-22 14:56 UTC, paresy requested changes
Anbei ein paar Kommentare

2020-10-22 14:56 UTC, paresy commented on Benachrichtigung/module.php
> +            parent::__construct($InstanceID, 'notification-response');
Ich glaube Niels hatte das schon mal angesprochen: Wir sollten die ID hinzufügen, da es mehrere Module geben kann, oder?

2020-10-22 14:56 UTC, paresy commented on Benachrichtigung/module.php
> +            $this->RegisterPropertyString('ActionNames', '[]');
Was hältst du von AdvancedResponseActions? Das würde mehr angeben, wozu es gehört?

2020-10-22 14:56 UTC, paresy commented on Benachrichtigung/module.php
> +                    '<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no">
Warum hast du dich entschieden es so komplex zu machen? (Ich glaube normale HTML Buttons hätten gereicht :)

2020-10-22 14:56 UTC, paresy commented on Benachrichtigung/module.php
> +            //$this->UpdateFormField('ActionNames', 'add', $ActionNames);
Wofür ist das?

2020-10-22 14:56 UTC, paresy commented on Benachrichtigung/module.php
> +                    echo '<h1>' . sprintf($this->Translate('Action %d was executed!'), $params['action']) . '</h1>';
Hier wäre der tatsächliche Name der Aktion cooler

2020-10-22 14:56 UTC, paresy commented on Benachrichtigung/module.php
> +                            $smsMessage = $action['title'] . ': ' . str_replace('{actions}', $smsLink, $message);
Wenn AdvancedResponse aus ist, ist $smsLink nicht definiert.

Ich fände besser, wenn die $smsMessage davor gebaut wird und das str_replace nur im If Block ist

2020-10-22 14:56 UTC, paresy commented on Benachrichtigung/module.php
> +                                $this->SendDebug('SMS', sprintf($this->Translate('Failed sending SMS - %d of 160 characters used'), strlen($smsMessage)), 0);
Schöne Erweiterung.

2020-10-22 14:56 UTC, paresy commented on Benachrichtigung/module.php
> +                        $message = str_replace('{variable}', strval(GetValue($action['messageVariable'])), $message);
Coole Verbesserung

2020-10-22 14:56 UTC, paresy commented on Benachrichtigung/module.php
> +                            $targetID = $this->GetIDForIdent('ResetScript');
Man könnte das ResetScript ja auch abschaffen und wenn AdvancedResponse aus ist, in die ResponseAction Variante nur ein generisches "Quittieren" Element einfügen. Dann kann das Skript weg und die TargetID lässt man immer auf InstanceID

2020-10-22 14:56 UTC, paresy commented on Benachrichtigung/module.php
> +                        'onAdd'    => 'BN_updateAdd($id, $ActionNames);',
Das macht nix laut der Funktion unten, oder?

2020-10-22 15:00 UTC, paresy commented on Benachrichtigung/module.php
> +                //Delete all associations
Das wirkt irgendwie an der falschen stelle, oder?

2020-10-23 07:51 UTC, TillBrede commented on Benachrichtigung/module.php
> +                    '<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no">
Eine rein optische entscheidung

2020-10-26 09:39 UTC, paresy requested changes
Noch was gefunden

2020-10-26 09:39 UTC, paresy commented on Benachrichtigung/module.php
> +            if ($SenderID == json_decode($this->GetBuffer('DTMF'))) {
GetBuffer kann beim start Leer liefern, was decoded wahrscheinlich ein false ist und was bei SenderID = 0 (was die KR_READY Meldung wäre) hier dann durchläuft und einen Fehler verursacht.

Ich würde hier nicht den Buffer nutzen, sondern direkt die korrekt ID anhand der VoIP Instanz ermitteln. Es wird ja selten aufgerufen und meiner Meinung ist es einfacher verständlich, sodass diese Performance-Optimierung nicht unbedingt notwendig ist :)

![image](https://user-images.githubusercontent.com/260376/97156554-2557f300-1777-11eb-8468-b619ec7f4725.png)

2020-11-05 12:26 UTC, paresy approved these changes

2020-11-05 12:26 UTC, merged